// Shared catalog — kept in sync with the PRODUCTS/RETAILERS arrays in
// index.html. This is what the background refresh job iterates over, and
// what the lookup endpoint uses as the canonical retailer list (it no
// longer trusts whatever the browser sends, for consistency + safety).

export const RETAILERS = [
  { name: "Evo Cycles", domain: "evocycles.co.nz" },
  { name: "99 Bikes", domain: "99bikes.co.nz" },
  { name: "Kiwivelo", domain: "kiwivelo.co.nz" },
  { name: "Hyper Ride", domain: "hyperride.co.nz" }
];

export const PRODUCTS = [
  // Mountain Bikes
  { name: "Talon 29 3", brand: "Giant", cat: "mtb" },
  { name: "Marlin 7", brand: "Trek", cat: "mtb" },
  { name: "Big Trail 400", brand: "Merida", cat: "mtb" },
  { name: "Xtrada 5", brand: "Polygon", cat: "mtb" },
  { name: "Fluid FS 3", brand: "Norco", cat: "mtb" },
  { name: "Chameleon", brand: "Santa Cruz", cat: "mtb" },
  { name: "Bobcat Trail 4", brand: "Marin", cat: "mtb" },
  { name: "Rockhopper Sport 29", brand: "Specialized", cat: "mtb" },
  { name: "Trail SE 4", brand: "Cannondale", cat: "mtb" },
  { name: "Aim SL", brand: "Cube", cat: "mtb" },
  { name: "MX 40", brand: "Orbea", cat: "mtb" },
  { name: "Neuron 7", brand: "Canyon", cat: "mtb" },
  { name: "One-Forty 400", brand: "Merida", cat: "mtb" },
  { name: "Stance 29 2", brand: "Giant", cat: "mtb" },
  { name: "Roscoe 7", brand: "Trek", cat: "mtb" },
  { name: "Storm 3", brand: "Norco", cat: "mtb" },
  { name: "Chisel Comp", brand: "Specialized", cat: "mtb" },
  { name: "5010", brand: "Santa Cruz", cat: "mtb" },
  { name: "Rift Zone 1", brand: "Marin", cat: "mtb" },
  { name: "Siskiu D6", brand: "Polygon", cat: "mtb" },
  { name: "Mahuika", brand: "Kona", cat: "mtb" },
  { name: "Avalanche Elite", brand: "GT", cat: "mtb" },
  // Road Bikes
  { name: "Domane AL 2", brand: "Trek", cat: "road" },
  { name: "Contend 3", brand: "Giant", cat: "road" },
  { name: "Scultura 400", brand: "Merida", cat: "road" },
  { name: "Strattos S5", brand: "Polygon", cat: "road" },
  { name: "Allez", brand: "Specialized", cat: "road" },
  { name: "Speedster 30", brand: "Scott", cat: "road" },
  { name: "Synapse 3", brand: "Cannondale", cat: "road" },
  { name: "Attain SL", brand: "Cube", cat: "road" },
  { name: "Avant H30", brand: "Orbea", cat: "road" },
  { name: "Endurace 7", brand: "Canyon", cat: "road" },
  { name: "Scultura Endurance 400", brand: "Merida", cat: "road" },
  { name: "Defy Advanced 3", brand: "Giant", cat: "road" },
  { name: "Émonda ALR 4", brand: "Trek", cat: "road" },
  { name: "Endurance SL R", brand: "Ribble", cat: "road" },
  { name: "SLR 8.9", brand: "Boardman", cat: "road" },
  { name: "Izalco Race 6.7", brand: "Focus", cat: "road" },
  // E-Bikes
  { name: "Explore E+ 3", brand: "Giant", cat: "ebike" },
  { name: "Verve+ 2", brand: "Trek", cat: "ebike" },
  { name: "Path E3", brand: "Polygon", cat: "ebike" },
  { name: "eSpresso City 400 EQ", brand: "Merida", cat: "ebike" },
  { name: "PL Carbon Pro", brand: "Amflow", cat: "ebike" },
  { name: "Turbo Vado 3.0", brand: "Specialized", cat: "ebike" },
  { name: "Tesoro Neo X 3", brand: "Cannondale", cat: "ebike" },
  { name: "Reaction Hybrid Race", brand: "Cube", cat: "ebike" },
  { name: "Gain D30", brand: "Orbea", cat: "ebike" },
  { name: "Pathlite:ON 6", brand: "Canyon", cat: "ebike" },
  { name: "eBig.Tour 400", brand: "Merida", cat: "ebike" },
  { name: "Trance X E+ 2", brand: "Giant", cat: "ebike" },
  { name: "Powerfly 4", brand: "Trek", cat: "ebike" },
  { name: "Turbo Levo Alloy", brand: "Specialized", cat: "ebike" },
  { name: "Fluid VLT 2", brand: "Norco", cat: "ebike" },
  { name: "Jam2 6.7", brand: "Focus", cat: "ebike" },
  // Kids & BMX
  { name: "ARX 20", brand: "Giant", cat: "kids" },
  { name: "Downtown 20", brand: "Haro", cat: "kids" },
  { name: "Rampage 24", brand: "Norco", cat: "kids" },
  { name: "Precaliber 20", brand: "Trek", cat: "kids" },
  { name: "Premier 3", brand: "Polygon", cat: "kids" },
  { name: "XTC Jr 24", brand: "Giant", cat: "kids" },
  { name: "Precaliber 24", brand: "Trek", cat: "kids" },
  { name: "Riprock 24", brand: "Specialized", cat: "kids" },
  { name: "Acid 240", brand: "Cube", cat: "kids" },
  { name: "Matts J24", brand: "Merida", cat: "kids" },
  { name: "Fluid 4 24", brand: "Norco", cat: "kids" },
  { name: "62", brand: "Frog", cat: "kids" },
  { name: "Beinn 24 Large", brand: "Islabikes", cat: "kids" },
  // Helmets
  { name: "Ventral Air MIPS", brand: "POC", cat: "helmets" },
  { name: "Chakra Plus", brand: "Kali Protectives", cat: "helmets" },
  { name: "Fixture MIPS", brand: "Giro", cat: "helmets" },
  { name: "Align II", brand: "Specialized", cat: "helmets" },
  { name: "Falcon XR MIPS", brand: "Bell", cat: "helmets" },
  { name: "Compact", brand: "Lazer", cat: "helmets" },
  { name: "Echo", brand: "MET", cat: "helmets" },
  { name: "Network MIPS", brand: "Smith", cat: "helmets" },
  { name: "ARO3", brand: "Oakley", cat: "helmets" },
  { name: "Camber", brand: "Specialized", cat: "helmets" },
  { name: "Syntax MIPS", brand: "Giro", cat: "helmets" },
  { name: "Z20 MIPS", brand: "Bell", cat: "helmets" },
  { name: "Mojito3", brand: "Kask", cat: "helmets" },
  { name: "StormChaser", brand: "Abus", cat: "helmets" },
  { name: "Primer MIPS", brand: "Sweet Protection", cat: "helmets" },
  { name: "FS260-Pro", brand: "Endura", cat: "helmets" },
  { name: "Starvos WaveCel", brand: "Bontrager", cat: "helmets" },
  { name: "Groove Plus", brand: "Scott", cat: "helmets" },
  { name: "Air Pro", brand: "Limar", cat: "helmets" },
  // Apparel
  { name: "Perfetto RoS Jacket", brand: "Castelli", cat: "apparel" },
  { name: "Free Aero RC Bib Shorts", brand: "Castelli", cat: "apparel" },
  { name: "Essential Road Jersey", brand: "POC", cat: "apparel" },
  { name: "Core Jersey", brand: "Rapha", cat: "apparel" },
  { name: "Zap Bib Knicks", brand: "Sugoi", cat: "apparel" },
  { name: "Gabba RoS Jersey", brand: "Castelli", cat: "apparel" },
  { name: "Ridecamp Gloves", brand: "100%", cat: "apparel" },
  { name: "Mille GT Jersey", brand: "Assos", cat: "apparel" },
  { name: "Aeron Bib Shorts", brand: "dhb", cat: "apparel" },
  { name: "Pro SL Jacket", brand: "Endura", cat: "apparel" },
  { name: "Attack Jersey", brand: "Pearl Izumi", cat: "apparel" },
  { name: "C5 Jacket", brand: "Gore Wear", cat: "apparel" },
  { name: "Bodyfit Pro Bib Shorts", brand: "Sportful", cat: "apparel" },
  { name: "Sport Jersey", brand: "Le Col", cat: "apparel" },
  { name: "Concept Jersey", brand: "Velocio", cat: "apparel" },
  { name: "Pro Team Bib Shorts", brand: "Rapha", cat: "apparel" },
  { name: "Entrata Jacket", brand: "Castelli", cat: "apparel" },
  { name: "RS Century Jersey", brand: "Sugoi", cat: "apparel" },
  { name: "Airmatic Jersey", brand: "100%", cat: "apparel" },
  // Parts & Components
  { name: "105 R7100 Groupset", brand: "Shimano", cat: "parts" },
  { name: "SPD-SL Pedals", brand: "Shimano", cat: "parts" },
  { name: "34 Float Performance Fork", brand: "Fox", cat: "parts" },
  { name: "Marathon Plus Tyre", brand: "Schwalbe", cat: "parts" },
  { name: "Grand Prix 5000 Tyre", brand: "Continental", cat: "parts" },
  { name: "Freewheel", brand: "White Industries", cat: "parts" },
  { name: "Deore M6100 Disc Brakes", brand: "Shimano", cat: "parts" },
  { name: "X11 Chain", brand: "KMC", cat: "parts" },
  { name: "Rival AXS Groupset", brand: "SRAM", cat: "parts" },
  { name: "GRX RX820 Groupset", brand: "Shimano", cat: "parts" },
  { name: "Pike Ultimate Fork", brand: "RockShox", cat: "parts" },
  { name: "XM 1700 Wheelset", brand: "DT Swiss", cat: "parts" },
  { name: "Ksyrium Wheelset", brand: "Mavic", cat: "parts" },
  { name: "303 Firecrest Wheelset", brand: "Zipp", cat: "parts" },
  { name: "Line Elite Wheelset", brand: "Bontrager", cat: "parts" },
  { name: "Chorus Groupset", brand: "Campagnolo", cat: "parts" },
  { name: "XX SL Eagle Cassette", brand: "SRAM", cat: "parts" },
  { name: "XT Rear Derailleur", brand: "Shimano", cat: "parts" },
  { name: "Minion DHF Tyre", brand: "Maxxis", cat: "parts" },
  { name: "Vulpine Tyre", brand: "WTB", cat: "parts" },
  { name: "Corsa Tyre", brand: "Vittoria", cat: "parts" },
  { name: "Works Crankset", brand: "Praxis", cat: "parts" },
  // Accessories
  { name: "Edge 130 Plus", brand: "Garmin", cat: "accessories" },
  { name: "Blinder Light Set", brand: "Knog", cat: "accessories" },
  { name: "New York Chain Lock", brand: "Kryptonite", cat: "accessories" },
  { name: "ProRide Roof Rack", brand: "Thule", cat: "accessories" },
  { name: "Mandible Bottle Cage", brand: "Arundel", cat: "accessories" },
  { name: "Back-Roller Panniers", brand: "Ortlieb", cat: "accessories" },
  { name: "Joe Blow Track Pump", brand: "Topeak", cat: "accessories" },
  { name: "Shoe Covers", brand: "VeloToze", cat: "accessories" },
  { name: "ELEMNT Bolt", brand: "Wahoo", cat: "accessories" },
  { name: "Micro Drive Light", brand: "Lezyne", cat: "accessories" },
  { name: "PCS-10 Stand", brand: "Park Tool", cat: "accessories" },
  { name: "Central Rear Rack", brand: "Blackburn", cat: "accessories" },
  { name: "Velocity Backpack", brand: "Ortlieb", cat: "accessories" },
  { name: "Raptor Hydration Pack", brand: "Osprey", cat: "accessories" },
  { name: "Blendr Mount", brand: "Bontrager", cat: "accessories" },
  { name: "Scoop Saddle", brand: "Fabric", cat: "accessories" },
  { name: "SLR Saddle", brand: "Selle Italia", cat: "accessories" },
  { name: "Tour Ride Tube", brand: "Continental", cat: "accessories" },
  { name: "Bike Cleaner Kit", brand: "Muc-Off", cat: "accessories" },
  { name: "Mattone Levers Kit", brand: "Silca", cat: "accessories" },
  { name: "Klic HP Pump", brand: "Crankbrothers", cat: "accessories" },
  { name: "Crave Backpack", brand: "POC", cat: "accessories" },
  // Nutrition
  { name: "Energy Gel Box (12)", brand: "Styrkr", cat: "nutrition" },
  { name: "Isotonic Energy Gel", brand: "Science in Sport", cat: "nutrition" },
  { name: "Energy Bar", brand: "Torq", cat: "nutrition" },
  { name: "Sport Electrolyte Tablets", brand: "Nuun", cat: "nutrition" },
  { name: "Endurance Fuel", brand: "Tailwind", cat: "nutrition" },
  { name: "Roctane Energy Gel", brand: "GU", cat: "nutrition" },
  { name: "Bloks Energy Chews", brand: "Clif", cat: "nutrition" },
  { name: "Gel 100", brand: "Maurten", cat: "nutrition" },
  { name: "PF 30 Gel", brand: "Precision Fuel", cat: "nutrition" },
  { name: "Perpetuem", brand: "Hammer Nutrition", cat: "nutrition" },
  { name: "Energy Gel", brand: "High5", cat: "nutrition" }
];

export function cacheKeyFor(brand, name) {
  return `price:${brand}|${name}`.toLowerCase();
}
